Repository ComputerSocietyVITC/Annual-Yearbook, pull requests merged in 2022-10, with the labels that each got.

#25 [ADD]: Adds action for GitHub Readme !
  .github/workflows/update_readme.yml
  template
Labels: documentation, enhancement, hacktoberfest

#30 Bug fixes
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/pull_request_template.md
  .github/workflows/cd.yaml
  ISSUE_TEMPLATE/bug_report.md
  gatsby-config.js
  package.json
  src/components/contributors.tsx
  src/components/main.jsx
  src/pages/404.js
  src/pages/index.js
  src/seo.jsx
  src/types/ContributorType.ts
Labels: enhancement, hacktoberfest

#20 [ADD]: Add contributors.md in the footer
  package.json
  src/components/contributors.tsx
  src/components/header.jsx
  src/components/main.jsx
  src/types/ContributorType.ts
Labels: enhancement, help wanted, hacktoberfest

#45 ISSUE#27 Resolve. DOCS Folder added
  docs/CONTRIBUTING_HOW_TO.md
Labels: documentation, hacktoberfest

#47 Timeline
  README.md
  src/components/javascript/main.jsx
  src/components/javascript/timeline.jsx
  src/styles/fonts/Montserrat-Bold.ttf
  src/styles/fonts/fonts.css
  src/styles/global.css
  src/styles/scrollbar.css
Labels: enhancement, help wanted, hacktoberfest
